test_that("zinb is the required structure", {
  model <- zinb()

  expect_s3_class(model, "extended.family")
  expect_s3_class(model, "family")
  expect_equal(model$family, "zero-inflated negative binomial")
  expect_type(model$link, "character")
  expect_type(model$linkfun, "closure")
  expect_type(model$linkinv, "closure")
  expect_type(model$dev.resids, "closure")
  expect_type(model$Dd, "closure")
  expect_type(model$rd, "closure")
  expect_type(model$residuals, "closure")
  expect_type(model$aic, "closure")
  expect_type(model$mu.eta, "closure")
  expect_null(model$g2g)
  expect_null(model$g3g)
  expect_null(model$g4g)
  expect_type(model$initialize, "expression")
  expect_type(model$postproc, "closure")
  expect_type(model$ls, "closure")
  expect_true(model$no.r.sq)
  expect_type(model$validmu, "closure")
  expect_type(model$valideta, "closure")
  expect_type(model$n.theta, "double")
  expect_equal(model$n.theta, 3)
  expect_type(model$predict, "closure")
  expect_vector(model$ini.theta, ptype = double(), size = 3)
  expect_type(model$putTheta, "closure")
  expect_type(model$getTheta, "closure")
  expect_type(model$saturated.ll, "closure")
})

test_that("lind works", {
  level <- 0
  r <- lind(5, c(1, 2, 0), level = level, b = 0)

  expect_equal(round(r$eta, 5), 37.94528)
  expect_equal(round(r$eta_g, 5), 7.38906)
  expect_equal(r$eta_gg, 0)
  expect_null(r$eta_th)
  expect_null(r$eta_gth)
  expect_null(r$eta_ggth)
  expect_null(r$eta_gggth)
  expect_null(r$eta_ggg)
  expect_null(r$eta_gggg)
  expect_null(r$eta_th2)
  expect_null(r$eta_gth2)
  expect_null(r$eta_ggth2)

  level <- 1
  r <- lind(25, c(8, 2.4, 6), level = level, b = 2)

  expect_equal(round(r$eta, 5), 333.57941)
  expect_equal(round(r$eta_g, 5), 13.02318)
  expect_equal(r$eta_gg, 0)
  expect_equal(r$eta_th[, 1], 1)
  expect_equal(round(r$eta_th[, 2], 5), 275.57941)
  expect_equal(r$eta_gth[, 1], 0)
  expect_equal(round(r$eta_gth[, 2], 5), 11.02318)
  expect_equal(r$eta_ggth[, 1], 0)
  expect_equal(r$eta_ggth[, 2], 0)
  expect_equal(r$eta_gggth[, 1], 0)
  expect_equal(r$eta_gggth[, 2], 0)
  expect_equal(r$eta_ggg, 0)
  expect_equal(r$eta_gggg, 0)
  expect_equal(r$eta_th2[, 1], 0)
  expect_equal(r$eta_th2[, 2], 0)
  expect_equal(round(r$eta_th2[, 3], 5), 275.57941)
  expect_equal(r$eta_gth2[, 1], 0)
  expect_equal(r$eta_gth2[, 2], 0)
  expect_equal(round(r$eta_gth2[, 3], 5), 11.02318)
  expect_equal(r$eta_ggth2[, 1], 0)
  expect_equal(r$eta_ggth2[, 2], 0)
  expect_equal(r$eta_ggth2[, 3], 0)
})
